### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by mghifariy** [allegro/bigcache#205]
**What is the issue you are having?**
`panic: runtime error: makeslice: len out of range`

```
goroutine 1 [running]:
github.com/allegro/bigcache/queue.NewBytesQueue(...)
        /Users/ghifari/go/pkg/mod/github.com/allegro/bigcache@v1.2.1/queue/bytes_queue.go:49
github.com/allegro/bigcache.initNewShard(0x400, 0x905c6fd34e800000, 0xc82e37e9a7400000, 0x7fe5cf2bea0000, 0x1f4, 0x1, 0x189bbe0, 0x1dede00, 0x2000, 0x0, ...)
        /Users/ghifari/go/pkg/mod/github.com/allegro/bigcache@v1.2.1/shard.go:250 +0x1b4
github.com/allegro/bigcache.newBigCache(0x400, 0x905c6fd34e800000, 0xc82e37e9a7400000, 0x7fe5cf2bea0000, 0x1f4, 0x1, 0x189bbe0, 0x1dede00, 0x2000, 0x0, ...)
        /Users/ghifari/go/pkg/mod/github.com/allegro/bigcache@v1.2.1/bigcache.go:75 +0x36b
github.com/allegro/bigcache.NewBigCache(...)
        /Users/ghifari/go/pkg/mod/github.com/allegro/bigcache@v1.2.1/bigcache.go:41
git.sstv.io/lib/go/gojunkyard.git/bigcache.New(0x400, 0x8bb2c97000, 0x45d964b800, 0x3e8, 0x1f4, 0x1, 0x2000, 0x0, 0xc0003a2000, 0x0)
        /Users/ghifari/go/pkg/mod/git.sstv.io/lib/go/gojunkyard.git@v0.0.0-20200213075828-fbdd21df871c/bigcache/bigcache.go:23 +0x154
main.serv()
        /Users/ghifari/work/chat/cmd/serv.go:55 +0x3cd
main.main.func1(0xc000287900, 0x1dede00, 0x0, 0x0)
        /Users/ghifari/work/chat/cmd/main.go:11 +0x20
github.com/spf13/cobra.(*Command).execute(0xc000287900, 0xc0000ac000, 0x0, 0x0, 0xc000287900, 0xc0000ac000)
        /Users/ghifari/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000287900, 0xc000151d08, 0x1, 0x1)
        /Users/ghifari/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ghifari/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/ghifari/work/chat/cmd/main.go:21 +0x187
exit status 2
```

**I have wrapped it for my library package to get the config value from .env file, here is my code:**
```
package bigcache

import (
	"time"

	"github.com/allegro/bigcache"
)

// Config holds all bigcache configuration
type Config struct {
	Shards             int           `envconfig:"SHARDS"`
	LifeWindow         time.Duration `envconfig:"LIFE_WINDOW"`
	CleanWindow        time.Duration `envconfig:"CLEAN_WINDOW"`
	MaxEntriesInWindow int           `envconfig:"MAX_ENTRIES_IN_WINDOW"`
	MaxEntrySize       int           `envconfig:"MAX_ENTRY_SIZE"`
	Verbose            bool          `envconfig:"VERBOSE"`
	HardMaxCacheSize   int           `envconfig:"HARD_MAX_CACHE_SIZE"`
}

// New instantiate bigcache based on configuration
func New(cfg Config) (*bigcache.BigCache, error) {
	bigcacheConfig := parseConfig(&cfg)
	return bigcache.NewBigCache(bigcacheConfig)
}

func parseConfig(cfg *Config) bigcache.Config {
	return bigcache.Config{
		Shards:             cfg.Shards,
		LifeWindow:         cfg.LifeWindow * time.Minute,
		CleanWindow:        cfg.CleanWindow * time.Minute,
		MaxEntriesInWindow: int(1000 * cfg.LifeWindow * 60),
		MaxEntrySize:       cfg.MaxEntrySize,
		Verbose:            cfg.Verbose,
		HardMaxCacheSize:   cfg.HardMaxCacheSize,
	}
}
```

Is there something wrong with my code?

**Comment by mghifariy** [comment]
nevermind, it's my fault. sorry to bothered you

**Comment by cristaloleg** [comment]
👍
