### ISSUE TITLE
queue: Push() panics in v3.0.0

### ISSUE THREAD

**Issue by ppai-plivo** [allegro/bigcache#263]
**What is the issue you are having?**

```
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/allegro/bigcache/v3/queue.(*BytesQueue).copy(...)
	/Users/prashanthpai/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/queue/bytes_queue.go:157
github.com/allegro/bigcache/v3/queue.(*BytesQueue).push(0xc00010ef08, 0xc00010eefd, 0xb, 0xb, 0xb)
	/Users/prashanthpai/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/queue/bytes_queue.go:142 +0x1a8
github.com/allegro/bigcache/v3/queue.(*BytesQueue).Push(0xc00010ef08, 0xc00010eefd, 0xb, 0xb, 0xc000100050, 0xc00010ef18, 0x1040f4a)
	/Users/prashanthpai/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/queue/bytes_queue.go:100 +0xb2
main.main()
	/Users/prashanthpai/bigcache-bug/main.go:7 +0x11c
```

**What is BigCache doing that it shouldn't?**

It's panicking. I haven't looked deeper but the the most likely cause is the integer underflow here which is hit when `capacity` passed to `NewBytesQueue` is `0`:
https://github.com/allegro/bigcache/blob/55d48f4e069fd81755c7be002903253d961abe44/queue/bytes_queue.go#L251

**This is a regression from `2.2.5`**

**Minimal, Complete, and Verifiable Example**

```go
package main

import "github.com/allegro/bigcache/v3/queue"

func main() {
	q := queue.NewBytesQueue(0, 1024, true)
	q.Push([]byte("hello world"))
}
```

**Environment:**

[bigcache v3.0.0](https://github.com/allegro/bigcache/releases/tag/v3.0.0)

```
$ go version
go version go1.15.2 darwin/amd64
```

**Comment by ljluestc** [comment]
```

package main

import (
	"fmt"
	"sync"
	"time"

	"github.com/allegro/bigcache/v3"
)

// CacheWithKeys wraps BigCache with a thread-safe key store
type CacheWithKeys struct {
	cache    *bigcache.BigCache
	keys     map[string]struct{}
	keysLock sync.RWMutex
}

// NewCacheWithKeys initializes a new CacheWithKeys
func NewCacheWithKeys(config bigcache.Config) (*CacheWithKeys, error) {
	// Wrap OnRemoveWithReason to catch panics
	config.OnRemoveWithReason = func(key string, entry []byte, reason bigcache.RemoveReason) {
		defer func() {
			if r := recover(); r != nil {
				fmt.Printf("Panic in OnRemoveWithReason: key=%s, reason=%v, error=%v\n", key, reason, r)
			}
		}()
		// Monitoring
		fmt.Printf("Removed key: %s, reason: %v\n", key, reason)
	}

	cache, err := bigcache.New(config)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize BigCache: %v", err)
	}

	return &CacheWithKeys{
		cache: cache,
		keys:  make(map[string]struct{}),
	}, nil
}

// Set stores a key-value pair and updates the key store
func (c *CacheWithKeys) Set(key string, value []byte) error {
	c.keysLock.Lock()
	defer c.keysLock.Unlock()

	if err := c.cache.Set(key, value); err != nil {
		return fmt.Errorf("failed to set key %s: %v", key, err)
	}
	c.keys[key] = struct{}{}
	return nil
}

// Get retrieves a value by key
func (c *CacheWithKeys) Get(key string) ([]byte, error) {
	return c.cache.Get(key)
}

// Delete removes a key-value pair and updates the key store
func (c *CacheWithKeys) Delete(key string) error {
	c.keysLock.Lock()
	defer c.keysLock.Unlock()

	if err := c.cache.Delete(key); err != nil {
		return fmt.Errorf("failed to delete key %s: %v", key, err)
	}
	delete(c.keys, key)
	return nil
}

// GetAllKeys returns all keys in the cache
func (c *CacheWithKeys) GetAllKeys() []string {
	c.keysLock.RLock()
	defer c.keysLock.RUnlock()

	keys := make([]string, 0, len(c.keys))
	for key := range c.keys {
		keys = append(keys, key)
	}
	return keys
}

func main() {
	// Configure BigCache
	expiry := 7 * time.Minute
	config := bigcache.DefaultConfig(expiry)
	config.CleanWindow = expiry               // Reduced to 7 minutes to clean more frequently
	config.HardMaxCacheSize = 8192           // 8GB
	config.Shards = 1024                     // Default shard count
	config.MaxEntriesInWindow = 1000         // Limit entries per shard
	config.MaxEntrySize = 1024               // 1KB max entry size
	config.Verbose = true                    // Enable logging

	// Initialize CacheWithKeys
	cache, err := NewCacheWithKeys(config)
	if err != nil {
		fmt.Printf("Error initializing cache: %v\n", err)
		return
	}

	// Simulate high Get load
	var wg sync.WaitGroup
	numWorkers := 100
	numOpsPerWorker := 1000

	for i := 0; i < numWorkers; i++ {
		wg.Add(1)
		go func(workerID int) {
			defer wg.Done()
			for j := 0; j < numOpsPerWorker; j++ {
				key := fmt.Sprintf("key-%d-%d", workerID, j)
				// Set entry
				if err := cache.Set(key, []byte(fmt.Sprintf("value-%d-%d", workerID, j))); err != nil {
					fmt.Printf("Worker %d: Set error: %v\n", workerID, err)
				}
				// Get entry
				if _, err := cache.Get(key); err != nil {
					fmt.Printf("Worker %d: Get error: %v\n", workerID, err)
				}
				// Small delay to simulate real workload
				time.Sleep(time.Millisecond)
			}
		}(i)
	}

	// Periodically print keys
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	go func() {
		for range ticker.C {
			keys := cache.GetAllKeys()
			fmt.Printf("Current keys (count=%d): %v\n", len(keys), keys[:min(5, len(keys))])
		}
	}()

	// Wait for workers
	wg.Wait()

	// Final key count
	keys := cache.GetAllKeys()
	fmt.Printf("Final keys (count=%d): %v\n", len(keys), keys[:min(5, len(keys))])
}

// min returns the minimum of two integers
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
```
