### ISSUE TITLE
panic: runtime error: index out of range [7] with length 0

### ISSUE THREAD

**Issue by lesterpang** [allegro/bigcache#283]
**What is the issue you are having?**

Run for a few seconds and panic

`panic: runtime error: index out of range [7] with length 0`

```
goroutine 60 [running]:
encoding/binary.littleEndian.Uint64(...)
        /usr/local/go/src/encoding/binary/binary.go:77
github.com/allegro/bigcache/v2.readTimestampFromEntry(...)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/encoding.go:58
github.com/allegro/bigcache/v2.(*cacheShard).onEvict(0xc00010cd80, 0xc0029a02fb, 0x0, 0x9845, 0x60f94108, 0xc000278f00, 0x0)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/shard.go:269 +0x85
github.com/allegro/bigcache/v2.(*cacheShard).set(0xc00010cd80, 0xc004e976f8, 0x13, 0x16c4e5b3aad5055c, 0xc004d785d8, 0x6, 0x6, 0x6, 0xc004d785d8)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/shard.go:132 +0x31a
github.com/allegro/bigcache/v2.(*BigCache).Set(0xc00009aea0, 0xc004e976f8, 0x13, 0xc004d785d8, 0x6, 0x6, 0x0, 0x0)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/bigcache.go:133 +0xac
main.main.func1(0xc00009aea0)
        /Users/lesterpang/go/src/wx-gitlab.xunlei.cn/vod/scheduler/manager/local_cache/example2/main.go:26 +0x7c
created by main.main
        /Users/lesterpang/go/src/wx-gitlab.xunlei.cn/vod/scheduler/manager/local_cache/example2/main.go:24 +0xf8
exit status 2

```

**Minimal, Complete, and Verifiable Example**

```
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/allegro/bigcache/v2"
)

func main() {
	bc, _ := bigcache.NewBigCache(bigcache.Config{
		Shards:             1024,
		LifeWindow:         time.Duration(1) * time.Second,
		CleanWindow:        time.Duration(1) * time.Second,
		MaxEntriesInWindow: 1,
		MaxEntrySize:       1,
		StatsEnabled:       true,
		Verbose:            true,
		HardMaxCacheSize:   100,
	})

	for i := 0; i < 100; i++ {
		go func() {
			for {
				_ = bc.Set(randPath(), randValue())
			}
		}()
	}

	select {}
}

func randPath() string {
	return fmt.Sprintf("%d", rand.Int())
}

func randValue() []byte {
	length := rand.Intn(1000)
	data := make([]byte, length)
	for i := 0; i < length; i++ {
		data[i] = byte(rand.Uint32())
	}
	return data
}
```

**Environment:**
- Version (git sha or release): v2.2.5
- OS: darwin/amd64
- go version: go1.16.6

**Comment by lesterpang** [comment]
Other panic in same verifiable  example

```
panic: runtime error: slice bounds out of range [:146622249] with capacity 46720

goroutine 22 [running]:
github.com/allegro/bigcache/v2/queue.(*BytesQueue).peek(0xc000250248, 0x16e2, 0x5382754343b577d6, 0x11a5860, 0xc00008dce0, 0x117b9e0, 0x117b9f0, 0xc000360ed0)
        /Users/xx/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/queue/bytes_queue.go:241 +0x185
github.com/allegro/bigcache/v2/queue.(*BytesQueue).Peek(...)
        /Users/xx/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/queue/bytes_queue.go:186
github.com/allegro/bigcache/v2.(*cacheShard).set(0xc000250240, 0xc00310ff50, 0x13, 0x5382754343b577d6, 0xc0031f8a00, 0x1e3, 0x1e3, 0x1e3, 0xc0031f8a00)
        /Users/xx/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/shard.go:131 +0xda
github.com/allegro/bigcache/v2.(*BigCache).Set(0xc00005a270, 0xc00310ff50, 0x13, 0xc0031f8a00, 0x1e3, 0x1e3, 0x0, 0x0)
        /Users/xx/go/pkg/mod/github.com/allegro/bigcache/v2@v2.2.5/bigcache.go:133 +0xac
main.main.func1(0xc00005a270)
        /Users/xx/go/src/x/vod/scheduler/manager/local_cache/example2/main.go:26 +0x7c
created by main.main
        /Users/xx/go/src/x/vod/scheduler/manager/local_cache/example2/main.go:24 +0xf8
exit status 2
```

**Comment by lesterpang** [comment]
Panic with v3.0.0

```
panic: runtime error: slice bounds out of range [:122072] with capacity 53056

goroutine 6 [running]:
github.com/allegro/bigcache/v3/queue.(*BytesQueue).peek(0xc00018c5a8, 0x3842, 0x7e, 0x977c, 0x60f9489e, 0xc000302e58, 0x1, 0x0)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/queue/bytes_queue.go:242 +0x185
github.com/allegro/bigcache/v3/queue.(*BytesQueue).Peek(...)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/queue/bytes_queue.go:186
github.com/allegro/bigcache/v3.(*cacheShard).cleanUp(0xc00018c5a0, 0x60f9489e)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/shard.go:280 +0x55
github.com/allegro/bigcache/v3.(*BigCache).cleanUp(0xc000064c30, 0x60f9489e)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/bigcache.go:215 +0x53
github.com/allegro/bigcache/v3.newBigCache.func1(0x400, 0x3b9aca00, 0x3b9aca00, 0x1, 0x1, 0x101, 0x10f8e28, 0x11a48b0, 0x64, 0x0, ...)
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/bigcache.go:92 +0x9b
created by github.com/allegro/bigcache/v3.newBigCache
        /Users/lesterpang/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.0/bigcache.go:86 +0x485
exit status 2
```

**Comment by lesterpang** [comment]
@janisz new panic simple demo

```
package main

import (
	"time"

	"github.com/allegro/bigcache/v2"
)

func main() {
	opt := bigcache.DefaultConfig(time.Second)
	opt.Shards = 2 << 10
	opt.MaxEntriesInWindow = 1024
	opt.MaxEntrySize = 1
	opt.HardMaxCacheSize = 1
	bc, _ := bigcache.NewBigCache(opt)

	_ = bc.Set("2225", make([]byte, 200))
	_ = bc.Set("8573", make([]byte, 100))
	_ = bc.Set("8573", make([]byte, 450))
	_ = bc.Set("7327", make([]byte, 300))
	_ = bc.Set("8573", make([]byte, 200))
}
```

**Comment by blackbeans** [comment]
i read bigcache source code and  found the panic  reason.

```go

func (s *cacheShard) set(key string, hashedKey uint64, entry []byte) error {
	currentTimestamp := uint64(s.clock.Epoch())
   
       .....

	if previousIndex := s.hashmap[hashedKey]; previousIndex != 0 {
		if previousEntry, err := s.entries.Get(int(previousIndex)); err == nil {
			resetKeyFromEntry(previousEntry)

			// need remove hashkey at the same time 
			delete(s.hashmap,hashedKey)
		}
	}

      .....

}

```

 if  the exist hashed key has been earsed  hashid , but the  new key  entry size maybe  bigger than  max shard size .
So ,the current  logic  uses  a loop to  remove oldest entries,but  when hashiid is zero ,the loop breaks.
But the hashmap still holds  hashed key index.
Next set the same key agains , the  s.entries  get a unexpect  []byte (or  zero length  slice ),
Finally resetKeyFromEntry method  throws a panic.


Solve :
add  this codes after   resetKeyFromEntry invoke:

```
  			// need remove hashkey at the same time 
			delete(s.hashmap,hashedKey)
```

**Comment by janisz** [comment]
@blackbeans that's awesome. How I could miss that.

**Comment by janisz** [comment]
This PR fixes:

- #283
- #254
- #250
- #234
- #226
- #222

**Comment by kurefm** [comment]
In theory, this issues is fix in v3.0.1, but I still met

```
runtime error: index out of range [7] with length 0

runtime/debug.Stack()
        /home/xx/Apps/go/src/runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0x120c9a0, 0xc26e4c02d0})
        /home/xx/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
        /home/xx/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/singleflight/singleflight.go:188 +0x3b
panic({0x120c9a0, 0xc26e4c02d0})
        /home/xx/Apps/go/src/runtime/panic.go:1038 +0x215
encoding/binary.littleEndian.Uint64(...)
        /home/xx/Apps/go/src/encoding/binary/binary.go:77
github.com/allegro/bigcache/v3.readTimestampFromEntry(...)
        /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/encoding.go:58
github.com/allegro/bigcache/v3.(*cacheShard).onEvict(0xc0edece368, {0xc377a92025, 0x50beccc039db3211, 0x0}, 0x0, 0x0)
        /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/shard.go:271 +0x65
github.com/allegro/bigcache/v3.(*cacheShard).set(0xc0edece360, {0xc2326b0550, 0x4d}, 0x0, {0xc0dc931800, 0x7e, 0x400})
        /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/shard.go:134 +0x1a5
github.com/xx/bigcache/v3.(*BigCache).Set(0xc0001b61a0, {0xc2326b0550, 0x4d}, {0xc0dc931800, 0x7e, 0x400})
        /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/bigcache.go:133 +0x8d
git.yfcloud.com/supercdn/supercdn_group/scheduler/minerpool/src/cache.(*customCache).Set(...)
        /home/xx/Codes/go/scdn/scheduler/minerpool/src/cache/custom_cache.go:59
```

**Comment by 784909593** [comment]
> In theory, this issues is fix in v3.0.1, but I still met
> 
> ```
> runtime error: index out of range [7] with length 0
> 
> runtime/debug.Stack()
>         /home/xx/Apps/go/src/runtime/debug/stack.go:24 +0x65
> golang.org/x/sync/singleflight.newPanicError({0x120c9a0, 0xc26e4c02d0})
>         /home/xx/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/singleflight/singleflight.go:35 +0x2c
> golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
>         /home/xx/.go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/singleflight/singleflight.go:188 +0x3b
> panic({0x120c9a0, 0xc26e4c02d0})
>         /home/xx/Apps/go/src/runtime/panic.go:1038 +0x215
> encoding/binary.littleEndian.Uint64(...)
>         /home/xx/Apps/go/src/encoding/binary/binary.go:77
> github.com/allegro/bigcache/v3.readTimestampFromEntry(...)
>         /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/encoding.go:58
> github.com/allegro/bigcache/v3.(*cacheShard).onEvict(0xc0edece368, {0xc377a92025, 0x50beccc039db3211, 0x0}, 0x0, 0x0)
>         /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/shard.go:271 +0x65
> github.com/allegro/bigcache/v3.(*cacheShard).set(0xc0edece360, {0xc2326b0550, 0x4d}, 0x0, {0xc0dc931800, 0x7e, 0x400})
>         /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/shard.go:134 +0x1a5
> github.com/xx/bigcache/v3.(*BigCache).Set(0xc0001b61a0, {0xc2326b0550, 0x4d}, {0xc0dc931800, 0x7e, 0x400})
>         /home/xx/.go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/bigcache.go:133 +0x8d
> git.yfcloud.com/supercdn/supercdn_group/scheduler/minerpool/src/cache.(*customCache).Set(...)
>         /home/xx/Codes/go/scdn/scheduler/minerpool/src/cache/custom_cache.go:59
> ```

@janis
I had the same problem with the same version, but it's hard to find a stable reproducible case. This problem will cause bigcache deadlock, and the hidden danger is very large.
