### ISSUE TITLE
bytesqueue peak panic

### ISSUE THREAD

**Issue by JamesSunXX** [allegro/bigcache#308]
found another panic 
```
panic: runtime error: slice bounds out of range [:231568609] with capacity 1170000

goroutine 82 [running]:
github.com/allegro/bigcache/v3/queue.(*BytesQueue).peek(0xc01104c6c8, 0x2177c, 0x35, 0xfc309, 0x62086973, 0xc0004ed640, 0x1, 0x0)
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/queue/bytes_queue.go:241 +0x185
github.com/allegro/bigcache/v3/queue.(*BytesQueue).Peek(...)
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/queue/bytes_queue.go:186
github.com/allegro/bigcache/v3.(*cacheShard).cleanUp(0xc01104c6c0, 0x62086973)
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/shard.go:282 +0x55
github.com/allegro/bigcache/v3.(*BigCache).cleanUp(0xc0004f69c0, 0x62086973)
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/bigcache.go:215 +0x53
github.com/allegro/bigcache/v3.newBigCache.func1(0x400, 0x1a3185c5000, 0x8bb2c97000, 0x927c0, 0x1f4, 0x0, 0x1b24e00, 0x2833cb8, 0x1000, 0x0, ...)
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/bigcache.go:92 +0x9b
created by github.com/allegro/bigcache/v3.newBigCache
	/root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.1/bigcache.go:86 +0x4a5
```

**Environment:**
- Version (git sha or release): v3.0.1
- OS (e.g. from `/etc/os-release` or winver.exe):
- go version: 1.15

**Comment by janisz** [comment]
@JamesSunXX Can you try v3.0.2
