### ISSUE TITLE
bytesqueue peak panic

### ISSUE THREAD

**Issue by tcsgogogo** [allegro/bigcache#338]
found a panic:
runtime error: slice bounds out of range [:31874] with capacity 24992
goroutine 1708235262 [running]:
panic({0x1618300, 0xc030365740})
        /data/golang/1.18/src/runtime/panic.go:838 +0x207
github.com/allegro/bigcache/v3/queue.(*BytesQueue).peek(0x140e960?, 0xc001730630?)
        /root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.2/queue/bytes_queue.go:242 +0x177
github.com/allegro/bigcache/v3/queue.(*BytesQueue).Get(...)
        /root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.2/queue/bytes_queue.go:193
github.com/allegro/bigcache/v3.(*cacheShard).getWrappedEntry(0xc0004f5200, 0xc06ab11d60?)
        /root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.2/shard.go:92 +0x46
github.com/allegro/bigcache/v3.(*cacheShard).get(0xc0004f5200, {0x18a8321, 0x1}, 0x1000000000001?)
        /root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.2/shard.go:64 +0x7e
github.com/allegro/bigcache/v3.(*BigCache).Get(0xc002c324e0, {0x18a8321, 0x1})
        /root/go/pkg/mod/github.com/allegro/bigcache/v3@v3.0.2/bigcache.go:123 +0x69

**Environment:**
- Version (git sha or release): v3.0.2
- OS (e.g. from `/etc/os-release` or winver.exe): centos 
- go version:  1.18

**Comment by janisz** [comment]
Do you have any way to reproduce it?

**Comment by janisz** [comment]
Interesting, what entries and keys looks like? Were the keys randomly distributed?

**Comment by tcsgogogo** [comment]
> Interesting, what entries and keys looks like? Were the keys randomly distributed?

1) In fact, both key and value are uint64 numbers.
2) The key comes from the uint64 number entered by the user, so it may not be randomly distributed.

Will data skew in a shard cause this problem? Shouldn't it cause a set error rather than a get error, let alone a panic.

**Comment by janisz** [comment]
> Will data skew in a shard cause this problem? Shouldn't it cause a set error rather than a get error, let alone a panic.

You are right. But maybe this approach will help us debug https://github.com/allegro/bigcache/issues/283

**Comment by tcsgogogo** [comment]
> > Will data skew in a shard cause this problem? Shouldn't it cause a set error rather than a get error, let alone a panic.
> 
> You are right. But maybe this approach will help us debug #283
PS:
I only use the set and get methods to access data. It seems that this is the easiest way to use.
func (c *BigCache) Set(key string, entry []byte) error 
func (c *BigCache) Get(key string) ([]byte, error)
