### ISSUE TITLE
compile a 32-bit LSB executable on arm and Execution error-> panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by 912929782** [allegro/bigcache#368]
**What is the issue you are having?**
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/GoSDK/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x13571684, 0x1)
        C:/GoSDK/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/allegro/bigcache/v3.(*cacheShard).hit(0x13571600, 0x5819c5d75cbda787)
        C:/Users/Joker/go/pkg/mod/github.com/allegro/bigcache/v3@v3.1.0/shard.go:403 +0x34
github.com/allegro/bigcache/v3.(*cacheShard).get(0x13571600, {0x214747, 0x4}, 0x5819c5d75cbda787)
        C:/Users/Joker/go/pkg/mod/github.com/allegro/bigcache/v3@v3.1.0/shard.go:79 +0x3d0
github.com/allegro/bigcache/v3.(*BigCache).Get(0x2498980, {0x214747, 0x4})
        C:/Users/Joker/go/pkg/mod/github.com/allegro/bigcache/v3@v3.1.0/bigcache.go:136 +0x8c

**Comment by janisz** [comment]
> On ARM, 386, and 32-bit MIPS, **it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically via the primitive atomic functions** (types [Int64](https://pkg.go.dev/sync/atomic#Int64) and [Uint64](https://pkg.go.dev/sync/atomic#Uint64) are automatically aligned). The first word in an allocated struct, array, or slice; in a global variable; or in a local variable (because the subject of all atomic operations will escape to the heap) can be relied upon to be 64-bit aligned.

https://pkg.go.dev/sync/atomic#pkg-notes

So maybe we should switch to `atomic.Int64` from `int64`

**Comment by janisz** [comment]
I see 3 options:
- move stats to the top of struct https://github.com/allegro/bigcache/blob/caa34156bfeab3aa547e18c21292736bbd2ae2c2/shard.go#L32
- use `atomic.Int64`
- instead of atomic use lock (that's already there) https://github.com/allegro/bigcache/blob/main/shard.go#L403-L406

@912929782 How to reproduce this issue? Does it happen with `go test ./...` we probably need to extend our CI with non x86 arch https://github.com/marketplace/actions/run-on-architecture

**Comment by 912929782** [comment]
I expect this problem to occur on x86 systems as well

**Comment by 912929782** [comment]
Forget to say, I am in the library: https://github.com/jpillora/overseer  to use bigcache operation, result in  this error. @janisz

**Comment by janisz** [comment]
We need to reproduce it, best in CI. Maybe we can use qemu for that :thinking:
